import type { IngredientAnalysisItem } from '../services/openaiIngredientAnalysisPrompt'
import { normalizeIngredientName } from './ingredientNameNormalization'

type TemplateDef = {
  canonical: string
  rating: IngredientAnalysisItem['rating']
  shortLabel: string
  headline: string
  labelDecoder: string
  whatItIs: string
  whatItDoes: string
  bodyEffect: string
  funFact: string
  whyItMattersYou: string
  ratingReason: string
  contextStat?: string
}

const TEMPLATE_DEFS: Record<string, TemplateDef> = {
  water: {
    canonical: 'water',
    rating: 'clean',
    shortLabel: 'Hydration base',
    headline: 'Basic hydration ingredient.',
    labelDecoder: 'Plain water used as a carrier or moisture source in the formula.',
    whatItIs: 'Water with no meaningful processing complexity in this context.',
    whatItDoes: 'Acts as a base liquid, helping dissolve and distribute other ingredients.',
    bodyEffect: 'Hydrates without adding calories, sugar, or additive load by itself.',
    funFact: 'When the label is short, water near the top usually means a less energy-dense product.',
    whyItMattersYou: 'This is generally a positive baseline line, not a processing red flag.',
    ratingReason: 'Whole-food baseline ingredient with minimal concern on its own.',
  },
  salt: {
    canonical: 'salt',
    rating: 'clean',
    shortLabel: 'Mineral seasoning',
    headline: 'Simple flavor mineral.',
    labelDecoder: 'Salt used to boost flavor contrast and round out sweetness or bitterness.',
    whatItIs: 'Sodium chloride, a basic mineral seasoning found in nearly all packaged foods.',
    whatItDoes: 'Enhances flavor impact and supports preservation in some formulas.',
    bodyEffect: 'Adds sodium load, which matters most when total daily sodium intake is high.',
    funFact: 'Small salt additions can make sweet products taste noticeably richer.',
    whyItMattersYou: 'Usually fine in small amounts, but frequent high-sodium foods can add up quickly.',
    ratingReason: 'Common baseline ingredient; concern depends more on total dietary sodium load.',
  },
  sugar: {
    canonical: 'sugar',
    rating: 'okay',
    shortLabel: 'Added sugar',
    headline: 'Refined sweetness source.',
    labelDecoder: 'Refined sugar added for immediate sweetness and broad flavor appeal.',
    whatItIs: 'A concentrated simple-carbohydrate sweetener with little fiber or protein.',
    whatItDoes: 'Drives sweetness, browning, and mouthfeel in processed foods.',
    bodyEffect: 'Absorbs quickly and can raise blood glucose without much satiety support.',
    funFact: 'If multiple sugar names appear, brands are often building a stacked sweetener system.',
    whyItMattersYou: 'Most useful as a frequency signal: occasional is easier to manage than daily.',
    ratingReason: 'Common added sweetener; acceptable contextually but still a refined sugar input.',
  },
  'coconut sugar': {
    canonical: 'coconut sugar',
    rating: 'okay',
    shortLabel: 'Unrefined-style sugar',
    headline: 'Less-refined sugar option.',
    labelDecoder: 'Sweetener from coconut sap that is often marketed as more natural.',
    whatItIs: 'A sugar source with slightly less refining than white table sugar.',
    whatItDoes: 'Adds sweetness while supporting flavor depth in bars and baked foods.',
    bodyEffect: 'Still behaves like added sugar in practice, even with a better marketing halo.',
    funFact: 'This sounds healthier than white sugar, but it remains a concentrated sweetener.',
    whyItMattersYou: 'Treat it as sugar exposure first, not as a major nutrition upgrade.',
    ratingReason: 'Refined sweetener category with modest upside over standard sugar at best.',
  },
  'maple syrup': {
    canonical: 'maple syrup',
    rating: 'clean',
    shortLabel: 'Natural syrup sweetener',
    headline: 'Tree-sap sweetener.',
    labelDecoder: 'Concentrated tree sap used for sweetness and characteristic maple flavor.',
    whatItIs: 'A minimally processed syrup compared with highly engineered industrial sweeteners.',
    whatItDoes: 'Sweetens while adding some flavor complexity beyond plain sugar.',
    bodyEffect: 'Still adds sugar load, though usually with less processing than many syrups.',
    funFact: 'A cleaner sweetener choice can still be high sugar if used heavily in the formula.',
    whyItMattersYou: 'Quality is better than many syrups, but portion and frequency still matter.',
    ratingReason: 'Minimally processed sweetener with stronger ingredient quality signal.',
  },
  honey: {
    canonical: 'honey',
    rating: 'clean',
    shortLabel: 'Natural sweetener',
    headline: 'Bee-made sweetener.',
    labelDecoder: 'Natural sweetener from bees used for flavor and sweetness.',
    whatItIs: 'A whole-food-adjacent sweetener with minimal industrial modification.',
    whatItDoes: 'Adds sweetness, mild floral notes, and binding in some products.',
    bodyEffect: 'Still contributes sugar energy quickly despite being less industrially processed.',
    funFact: 'Honey is often a quality signal, but it does not cancel out total sugar load.',
    whyItMattersYou: 'Better ingredient quality than many refined syrups, with the same moderation rule.',
    ratingReason: 'Recognizable minimally processed sweetener with cleaner sourcing signal.',
  },
  'baking soda': {
    canonical: 'baking soda',
    rating: 'okay',
    shortLabel: 'Leavening mineral',
    headline: 'Basic leavening agent.',
    labelDecoder: 'Leavening ingredient that helps doughs rise and lighten texture.',
    whatItIs: 'Sodium bicarbonate, a standard baking aid used in home and industrial baking.',
    whatItDoes: 'Creates gas during baking, improving structure and lift.',
    bodyEffect: 'Used in small amounts and generally not a major concern by itself.',
    funFact: 'This is mostly a texture/structure tool rather than a nutrition driver.',
    whyItMattersYou: 'Usually a neutral processing line unless sodium is a strict concern for you.',
    ratingReason: 'Common functional baking input with low standalone risk in normal amounts.',
  },
  'baking powder': {
    canonical: 'baking powder',
    rating: 'okay',
    shortLabel: 'Leavening blend',
    headline: 'Multi-part leavening blend.',
    labelDecoder: 'Leavening mix used to create lift and softness in baked textures.',
    whatItIs: 'A blend of bicarbonate and acids designed for consistent rising.',
    whatItDoes: 'Produces gas during baking to improve crumb and texture.',
    bodyEffect: 'Generally low-impact at recipe amounts, with function mostly in product structure.',
    funFact: 'Another classic manufacturing-function ingredient: texture first, nutrition second.',
    whyItMattersYou: 'Usually not the main decision driver unless you are screening sodium closely.',
    ratingReason: 'Standard baking functional input with modest processing but low concern.',
  },
  yeast: {
    canonical: 'yeast',
    rating: 'okay',
    shortLabel: 'Fermentation starter',
    headline: 'Fermentation ingredient.',
    labelDecoder: 'Microbial leavening ingredient used for rise and flavor development.',
    whatItIs: 'A fermentation organism commonly used in bread and dough systems.',
    whatItDoes: 'Creates gas and fermentation notes that shape structure and taste.',
    bodyEffect: 'Typically a low-risk functional ingredient at normal food amounts.',
    funFact: 'Yeast is one of the few processing helpers that also improves flavor complexity.',
    whyItMattersYou: 'Usually a positive/neutral functional line rather than an additive red flag.',
    ratingReason: 'Established food fermentation ingredient with low standalone concern.',
  },
  'olive oil': {
    canonical: 'olive oil',
    rating: 'clean',
    shortLabel: 'Monounsaturated fat',
    headline: 'Higher-quality culinary oil.',
    labelDecoder: 'Oil from olives used for fat, mouthfeel, and flavor.',
    whatItIs: 'A less industrial fat source compared with many refined blended oils.',
    whatItDoes: 'Adds smooth texture and energy density while improving flavor profile.',
    bodyEffect: 'Provides primarily monounsaturated fats that fit better in many dietary patterns.',
    funFact: 'In mixed-oil products, olive oil is often a quality signal worth noticing.',
    whyItMattersYou: 'A generally better fat line, though total fat load and portions still count.',
    ratingReason: 'Recognizable minimally processed culinary oil with favorable quality signal.',
  },
  'coconut oil': {
    canonical: 'coconut oil',
    rating: 'clean',
    shortLabel: 'Stable tropical fat',
    headline: 'Shelf-stable plant fat.',
    labelDecoder: 'Oil from coconut used for creamy texture and stability.',
    whatItIs: 'A plant-derived fat with high saturated-fat content.',
    whatItDoes: 'Improves mouthfeel and helps products stay stable at room temperature.',
    bodyEffect: 'Provides quick fat energy but can raise saturated fat intake when frequent.',
    funFact: 'Great for texture engineering, so context and amount matter more than the label halo.',
    whyItMattersYou: 'Quality is generally better than hydrogenated fats, with a saturated-fat tradeoff.',
    ratingReason: 'Recognizable fat source; clean ingredient signal with moderation tradeoff.',
  },
  'avocado oil': {
    canonical: 'avocado oil',
    rating: 'clean',
    shortLabel: 'Monounsaturated oil',
    headline: 'Avocado-derived fat source.',
    labelDecoder: 'Oil from avocado used for texture and fat balance.',
    whatItIs: 'A culinary oil generally positioned as a higher-quality plant fat.',
    whatItDoes: 'Adds smoothness, energy density, and helps carry flavor.',
    bodyEffect: 'Provides monounsaturated fats and tends to fit cleaner-fat preferences.',
    funFact: 'When present in short ingredient lists, this is often a quality fat signal.',
    whyItMattersYou: 'Usually a positive fat line, though total calories from oils still accumulate.',
    ratingReason: 'Recognizable minimally processed oil with favorable ingredient-quality profile.',
  },
  peanuts: {
    canonical: 'peanuts',
    rating: 'clean',
    shortLabel: 'Whole legume nut',
    headline: 'Whole-food protein/fat base.',
    labelDecoder: 'Whole peanuts used as a core food ingredient rather than an additive.',
    whatItIs: 'A minimally processed whole food providing fats, protein, and micronutrients.',
    whatItDoes: 'Builds structure, flavor, and satiety in spreads and snack products.',
    bodyEffect: 'Digests slower than refined carbs, helping fullness and steadier energy.',
    funFact: 'When peanuts lead the list, the formula is usually closer to whole-food structure.',
    whyItMattersYou: 'Strong quality signal unless you have a peanut allergy.',
    ratingReason: 'Whole-food ingredient with good baseline nutrition density and low processing.',
  },
  'roasted peanuts': {
    canonical: 'roasted peanuts',
    rating: 'clean',
    shortLabel: 'Roasted whole peanuts',
    headline: 'Roasted whole-food base.',
    labelDecoder: 'Whole peanuts roasted to deepen flavor and reduce raw notes.',
    whatItIs: 'A minimally processed whole-food ingredient with simple heat treatment.',
    whatItDoes: 'Provides core texture, nut flavor, and satiety-supportive fats/protein.',
    bodyEffect: 'Supports fullness better than refined-carb snack bases at similar calories.',
    funFact: 'Roasting changes flavor far more than nutrition profile in most peanut products.',
    whyItMattersYou: 'Usually a high-quality base line unless allergy risk applies.',
    ratingReason: 'Whole-food ingredient with simple processing and strong quality signal.',
  },
  'wheat flour': {
    canonical: 'wheat flour',
    rating: 'okay',
    shortLabel: 'Refined grain base',
    headline: 'Refined flour structure base.',
    labelDecoder: 'Milled wheat flour used as a low-cost structure ingredient in baked products.',
    whatItIs: 'A grain flour that can be nutritionally lighter than whole-grain forms.',
    whatItDoes: 'Creates dough structure, chew, and bulk in baked formulas.',
    bodyEffect: 'Typically digests faster than whole-grain forms and may be less filling.',
    funFact: 'In sweets, refined flour often works with sugar as a fast-digesting carb base.',
    whyItMattersYou: 'Useful context for satiety goals: this is more structure than nutrient density.',
    ratingReason: 'Common processed grain base with neutral-to-moderate quality profile.',
  },
  'corn starch': {
    canonical: 'corn starch',
    rating: 'okay',
    shortLabel: 'Refined starch thickener',
    headline: 'Refined starch helper.',
    labelDecoder: 'Extracted corn starch used mainly to thicken, bind, or adjust texture.',
    whatItIs: 'A purified starch fraction with little fiber or protein.',
    whatItDoes: 'Improves consistency and mouthfeel in sauces, fillings, and baked foods.',
    bodyEffect: 'Acts as a fast-digesting carbohydrate when present in meaningful amounts.',
    funFact: 'Often a texture tool first, not a nutrition upgrade.',
    whyItMattersYou: 'Worth tracking if you are trying to lower refined-carb load.',
    ratingReason: 'Standard processed thickener with neutral functional role and limited nutrient value.',
  },
  'vegetable oil': {
    canonical: 'vegetable oil',
    rating: 'okay',
    shortLabel: 'Refined blended oil',
    headline: 'Generic refined fat blend.',
    labelDecoder: 'A broad label for blended/refined plant oils used for cost and consistency.',
    whatItIs: 'A mixed refined oil input rather than a single clearly named fat source.',
    whatItDoes: 'Improves texture, mouthfeel, and shelf stability at low cost.',
    bodyEffect: 'Adds calorie-dense fat without much satiety advantage by itself.',
    funFact: 'Generic oil naming is often a transparency signal: quality can vary by source blend.',
    whyItMattersYou: 'Not automatically bad, but less informative than clearly named single-source oils.',
    ratingReason: 'Functional refined fat category with moderate processing and variable quality.',
  },
  'natural flavor': {
    canonical: 'natural flavor',
    rating: 'concerning',
    shortLabel: 'Undisclosed flavor blend',
    headline: 'Flavor system placeholder.',
    labelDecoder: 'Broad label for extracted flavor compounds without full public formula detail.',
    whatItIs: 'A proprietary flavor blend where exact compounds are not fully listed on-pack.',
    whatItDoes: 'Amplifies taste consistency and palatability across large production batches.',
    bodyEffect: 'Usually used in small amounts, but offers little nutrition and limited transparency.',
    funFact: 'This line is often about flavor engineering, not ingredient simplicity.',
    whyItMattersYou: 'Useful flag if you prioritize simple, fully transparent ingredient lists.',
    ratingReason: 'Low-transparency flavor additive category flagged by Fillr deterministic rules.',
  },
  'cocoa butter': {
    canonical: 'cocoa butter',
    rating: 'okay',
    shortLabel: 'Chocolate fat base',
    headline: 'Cacao-derived fat.',
    labelDecoder: 'Natural fat from cacao beans that gives chocolate smooth melt and body.',
    whatItIs: 'A cocoa-derived fat used as a core texture ingredient in chocolate systems.',
    whatItDoes: 'Creates melt-in-mouth texture and stabilizes chocolate structure.',
    bodyEffect: 'Provides energy-dense fat; impact depends on overall sugar/fat context of the product.',
    funFact: 'Often one of the better chocolate ingredients, but the surrounding sugar matrix still matters most.',
    whyItMattersYou: 'Quality fat signal in chocolate, though not a standalone health upgrade.',
    ratingReason: 'Common chocolate fat ingredient with moderate processing and neutral quality profile.',
  },
  'unsweetened chocolate': {
    canonical: 'unsweetened chocolate',
    rating: 'okay',
    shortLabel: 'Cocoa solids base',
    headline: 'Cocoa solids ingredient.',
    labelDecoder: 'Chocolate solids without added sugar, used for cocoa depth and bitterness.',
    whatItIs: 'A cocoa-rich ingredient that carries core chocolate flavor compounds.',
    whatItDoes: 'Builds flavor backbone and balances sweetness in chocolate formulas.',
    bodyEffect: 'Contributes cocoa compounds, though final effect depends on the full product formula.',
    funFact: 'This is usually a stronger quality signal than generic flavored chocolate coatings.',
    whyItMattersYou: 'A comparatively better chocolate line, especially when not drowned by added sugars.',
    ratingReason: 'Core cocoa ingredient with moderate processing and decent ingredient-quality signal.',
  },
}

export function buildIngredientTemplateItem(labelName: string): IngredientAnalysisItem | null {
  const key = normalizeIngredientName(labelName)
  const t = TEMPLATE_DEFS[key]
  if (!t) return null
  const name = String(labelName ?? '').trim() || t.canonical
  return {
    name,
    ingredient_name: name,
    shortLabel: t.shortLabel,
    whyItMattersBullets: [
      t.whatItDoes,
      t.whyItMattersYou,
    ] as readonly [string, string],
    systemJudgment: t.whyItMattersYou,
    impactForYou: t.whyItMattersYou,
    ...(t.rating === 'avoid' || t.rating === 'concerning' ? { flagDriver: 'processing' as const } : {}),
    profileAnchor: key,
    actionability: t.rating === 'avoid' ? 'avoid' : t.rating === 'concerning' ? 'limit' : 'okay',
    intelligenceConfidence: 'high',
    headline: t.headline,
    labelDecoder: t.labelDecoder,
    whatItIs: t.whatItIs,
    whatItDoes: t.whatItDoes,
    bodyEffect: t.bodyEffect,
    funFact: t.funFact,
    whyItMattersYou: t.whyItMattersYou,
    rating: t.rating,
    ratingReason: t.ratingReason,
    contextStat: t.contextStat ?? '',
    ratingSource: 'deterministic',
    from_cache: false,
  }
}

